# Generated by Django 3.2.9 on 2021-11-10 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('address', models.CharField(max_length=300)),
                ('pincode', models.CharField(max_length=6)),
                ('mobile', models.CharField(max_length=10, unique=True)),
            ],
        ),
    ]
